#ifndef options_h
#define options_h

#define YOVERSION "0.9.434m-r2-alpha.s8.1H-E"

/*******************************************************
DO NOT EDIT THIS FILE. 
ALL YOUR SETTINGS WILL BE OVERWRITTEN DURING THE UPDATE.
STORE YOUR SETTINGS IN THE *** myoptions.h *** FILE.
********************************************************/

#if __has_include("../../myoptions.h")
  #include "../../myoptions.h"        /* <- write your variable values here */
#endif
#if __has_include("../../mqttoptions.h")
  #include "../../mqttoptions.h"
#endif
/*******************************************************

The connection tables are located here https://github.com/e2002/yoradio#connection-tables
   
********************************************************/

#define DSP_ST7701      28    // 480x480  4.0'  ESP32-4848S040 RGB Panel https://aliexpress.ru/item/1005008214872438.html

#ifndef DSP_MODEL
  #define DSP_MODEL  DSP_ST7701
#endif
#ifndef DSP_HSPI
  #define DSP_HSPI   false      // use HSPI for displays (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif
#ifndef LED_INVERT
  #define LED_INVERT   false      // invert onboard LED?
#endif

/*        TFT DISPLAY             */
#ifndef TFT_CS
  #define TFT_CS        5
#endif
#ifndef TFT_RST
  #define TFT_RST       -1   // Or set to -1 and connect to Esp EN pin
#endif
#ifndef TFT_DC
  #define TFT_DC        4
#endif

/*        NEXTION                 */
#ifndef NEXTION_RX
  #define NEXTION_RX    255
#endif
#ifndef NEXTION_TX
  #define NEXTION_TX    255
#endif

/*        OLED I2C DISPLAY        */
#ifndef I2C_SDA
  #define I2C_SDA 21
#endif
#ifndef I2C_SCL
  #define I2C_SCL 22
#endif
#ifndef I2C_RST
  #define I2C_RST -1
#endif

/*        VS1053                  */
#ifndef VS1053_CS
  #define VS1053_CS     255 // 27
#endif
#ifndef VS1053_DCS
  #define VS1053_DCS    25
#endif
#ifndef VS1053_DREQ
  #define VS1053_DREQ   26
#endif
#ifndef VS1053_RST
  #define VS1053_RST    -1    // set to -1 if connected to Esp EN pin
#endif
#ifndef VS_HSPI
  #define VS_HSPI   false      // use HSPI for VS1053 (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif
#ifndef VS_SSPI
  #define VS_SSPI   false      // ESP32-S3: use SubSPI for VS1053 (miso=37, mosi=35, clk=36) instead of FSPI (by default)
#endif

/*        I2S DAC                 */
#ifndef I2S_DOUT
  #define I2S_DOUT      27  // DIN connection
#endif
#ifndef I2S_BCLK
  #define I2S_BCLK      26  // BCLK Bit clock
#endif
#ifndef I2S_LRC
  #define I2S_LRC       25  // WSEL Left Right Clock
#endif

/*        SDCARD                  */
#ifndef USE_SD
  #define USE_SD         false  // Enable SD card support
#endif
#ifndef SDC_CS
  #define SDC_CS        255  // SDCARD CS pin
#endif
#ifndef SD_SCK
  #define SD_SCK        255  // SDCARD SCK pin
#endif
#ifndef SD_MISO
  #define SD_MISO       255  // SDCARD MISO pin
#endif
#ifndef SD_MOSI
  #define SD_MOSI       255  // SDCARD MOSI pin
#endif
#ifndef SD_HSPI
  #define SD_HSPI       false  // use HSPI for SD (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif
#ifndef SD_DEBUG_ENABLED
  #define SD_DEBUG_ENABLED false  // Enable SD card debugging
#endif
// LVGL pointer pipeline trace (Serial): DOWN/MOVE/UP, suppress-after-wake, Station short-click decisions.
// Трассировка тача LVGL (Serial): нажатие/движение/отпускание, suppress после пробуждения, решения Station.
#ifndef YORADIO_LVGL_TOUCH_DEBUG
  #define YORADIO_LVGL_TOUCH_DEBUG 0
#endif
// Block 8-E5C: carousel PageChain lv_scr_load_anim (MOVE_LEFT/RIGHT). 0=instant goTo on partial builds.
// Block 8-E5C: анимация карусели PageChain. 0=мгновенный goTo (4848 partial); 1=slide (быстрые платы / Settings позже).
#ifndef YORADIO_LVGL_PAGE_TRANSITION_ANIM_DEFAULT
  #define YORADIO_LVGL_PAGE_TRANSITION_ANIM_DEFAULT 0
#endif
#ifndef SDSPISPEED
  #define SDSPISPEED    20000000  // SD SPI speed in Hz
#endif

/*        ENCODER                 */
#ifndef ENC_BTNL
  #define ENC_BTNL              255
#endif
#ifndef ENC_BTNB
  #define ENC_BTNB              255
#endif
#ifndef ENC_BTNR
  #define ENC_BTNR              255
#endif
#ifndef ENC_INTERNALPULLUP                // Thanks for Buska1968. See this topic: https://4pda.to/forum/index.php?s=&showtopic=1010378&view=findpost&p=113385448
  #define ENC_INTERNALPULLUP    true
#endif
#ifndef ENC_HALFQUARD
  #define ENC_HALFQUARD         false
#endif

#ifndef ENC2_BTNL
  #define ENC2_BTNL              255
#endif
#ifndef ENC2_BTNB
  #define ENC2_BTNB              255
#endif
#ifndef ENC2_BTNR
  #define ENC2_BTNR              255
#endif
#ifndef ENC2_INTERNALPULLUP
  #define ENC2_INTERNALPULLUP    true
#endif
#ifndef ENC2_HALFQUARD
  #define ENC2_HALFQUARD         false
#endif

/*        BUTTONS                 */
#ifndef BTN_LEFT
  #define BTN_LEFT              255
#endif
#ifndef BTN_CENTER
  #define BTN_CENTER            255
#endif
#ifndef BTN_RIGHT
  #define BTN_RIGHT             255
#endif
#ifndef BTN_UP
  #define BTN_UP            255
#endif
#ifndef BTN_DOWN
  #define BTN_DOWN             255
#endif
#ifndef BTN_MODE
  #define BTN_MODE             255
#endif
#ifndef BTN_INTERNALPULLUP
  #define BTN_INTERNALPULLUP    true
#endif
#ifndef BTN_LONGPRESS_LOOP_DELAY
  #define BTN_LONGPRESS_LOOP_DELAY    200   // delay between calling DuringLongPress event
#endif
#ifndef BTN_CLICK_TICKS
  #define BTN_CLICK_TICKS    300
#endif
#ifndef BTN_PRESS_TICKS
  #define BTN_PRESS_TICKS    500
#endif

/*        TOUCH SCREEN            */
#define TS_MODEL_UNDEFINED      0
#define TS_MODEL_XPT2046        1
#define TS_MODEL_GT911          2
#define TS_MODEL_AXS15231B      3
#define TS_MODEL_CST826         4

#ifndef TS_MODEL
  #define TS_MODEL              TS_MODEL_UNDEFINED
#endif

#ifndef TS_CS
  #define TS_CS                 13
#endif
#ifndef TS_SDA
  #define TS_SDA                33
#endif
#ifndef TS_SCL
  #define TS_SCL                32
#endif
#ifndef TS_INT
  #define TS_INT                21
#endif
#ifndef TS_RST
  #define TS_RST                25
#endif

#ifndef TS_HSPI
  #define TS_HSPI   false      // use HSPI for touchscreen (miso=12, mosi=13, clk=14) instead of VSPI (by default)
#endif

/*        LCD DISPLAY            */
#ifndef LCD_RS
  #define LCD_RS                255
#endif
#ifndef LCD_E
  #define LCD_E                 255
#endif
#ifndef LCD_D4
  #define LCD_D4                255
#endif
#ifndef LCD_D5
  #define LCD_D5                255
#endif
#ifndef LCD_D6
  #define LCD_D6                255
#endif
#ifndef LCD_D7
  #define LCD_D7                255
#endif

/*        RTC                     */
#define RTC_MODULE_UNDEFINED    0
#define DS3231                  1
#define DS1307                  2

#ifndef RTC_MODULE
  #define RTC_MODULE            RTC_MODULE_UNDEFINED  /*  DS3231 or DS1307  */
#endif
#ifndef RTC_SDA
  #define RTC_SDA               255
#endif
#ifndef RTC_SCL
  #define RTC_SCL               255
#endif

/*        ESP DEVBOARD            */
#if defined(ARDUINO_ESP32S3_DEV) || defined(ARDUINO_ESP32C3_DEV)
    #define ESP_S3C3       1
    #ifndef USE_BUILTIN_LED
      #define USE_BUILTIN_LED true
    #endif
    #ifndef LED_BUILTIN_S3
      #define LED_BUILTIN_S3   255
    #endif
    #if USE_BUILTIN_LED
      #define REAL_LEDBUILTIN LED_BUILTIN
    #else
      #define REAL_LEDBUILTIN LED_BUILTIN_S3
    #endif
#else
    #ifndef LED_BUILTIN
      #define LED_BUILTIN   255
    #endif
    #define REAL_LEDBUILTIN LED_BUILTIN
#endif

/*        Other settings. You can overwrite them in the myoptions.h file        */
#ifndef MUTE_PIN
  #define MUTE_PIN      255   // MUTE Pin
#endif
#ifndef MUTE_VAL
  #define MUTE_VAL      HIGH  // Write this to MUTE_PIN when player is stopped
#endif
#ifndef MUTE_LOCK
  #define MUTE_LOCK      false  // for vs1053 Shield rev2 - lock MUTE_PIN to !MUTE_VAL
#endif
#ifndef BRIGHTNESS_PIN
  #define BRIGHTNESS_PIN 255   // BRIGHTNESS Pin
#endif
#ifndef PLAYER_FORCE_MONO
  #define PLAYER_FORCE_MONO      false  // mono option - false stereo, true mono
#endif
#ifndef I2S_INTERNAL
  #define I2S_INTERNAL      false  // If true - use esp32 internal DAC
#endif
#ifndef ROTATE_90
  #define ROTATE_90         false  // Optional 90 degree rotation for square displays
#endif
#ifndef WAKE_PIN
  #define WAKE_PIN      255   // Wake Pin (for manual wakeup from sleep mode. can match with BTN_XXXX, ENC_BTNB, ENC2_BTNB.  must be one of: 0,2,4,12,13,14,15,25,26,27,32,33,34,35,36,39)
#endif
#ifndef LIGHT_SENSOR
  #define LIGHT_SENSOR  255   // Light sensor
#endif
#ifndef AUTOBACKLIGHT
  #ifndef AUTOBACKLIGHT_MAX
    #define AUTOBACKLIGHT_MAX          2500
  #endif
  #ifndef AUTOBACKLIGHT_MIN
    #define AUTOBACKLIGHT_MIN          12
  #endif
  #define AUTOBACKLIGHT(x) ({uint16_t _lh=(x>AUTOBACKLIGHT_MAX?AUTOBACKLIGHT_MAX:x); map(_lh, AUTOBACKLIGHT_MAX, 0, AUTOBACKLIGHT_MIN, 100);})  // autobacklight function
#endif
#ifndef EXT_WEATHER
  #define EXT_WEATHER       true   // Extended weather
#endif
#ifndef RSSI_DIGIT
  #define RSSI_DIGIT       false   // Extended weather
#endif
#ifndef RSSI_STEPS
  #define RSSI_STEPS       -50,-60,-70,-80
#endif
#ifndef CLOCKFONT_MONO
  #define CLOCKFONT_MONO   true     // monospace clock font
#endif
#ifndef MAX_AUDIO_SOCKET_TIMEOUT
  #define MAX_AUDIO_SOCKET_TIMEOUT   false     // max audio socket timeout?
#endif
#ifndef BITRATE_FULL
  #define BITRATE_FULL     true   // display bitreta badget
#endif
#ifndef SD_AUTOPLAY
  #define SD_AUTOPLAY      true   // auto play from SD card when inserted
#endif
#ifndef SD_MAX_LEVELS
  #define SD_MAX_LEVELS      3      //  search depth for files on the SD card
#endif

/*
*** ST7735 display submodel ***
  INITR_BLACKTAB        // 1.8' https://aliexpress.ru/item/1005002822797745.html
      See this note If INITR_BLACKTAB have a noisy line on one side of the screen https://github.com/e2002/yoradio#note-if-initr_blacktab-dsp-have-a-noisy-line-on-one-side-of-the-screen-then-in-adafruit_st7735cpp
  INITR_144GREENTAB     // 1.44' https://aliexpress.ru/item/1005002822797745.html
  INITR_MINI160x80      // 0.96' 160x80 ST7735S   https://????
  INITR_GREENTAB
  INITR_REDTAB
 */
#ifndef DTYPE
  #define DTYPE INITR_BLACKTAB
#endif

/*        IR                      */
#ifndef IR_PIN
  #define IR_PIN                255
#endif
#ifndef IR_TIMEOUT
  #define IR_TIMEOUT            80        // kTimeout, see IRremoteESP8266 documentation
#endif

#define EN  1
#define RU  2
#ifndef L10N_LANGUAGE
  #define L10N_LANGUAGE EN
#endif

#ifdef VSPI
#define VOOPSENb VSPI
#else
#define VOOPSENb 3
#endif

#ifdef HSPI
#define HOOPSENb HSPI
#else
#define HOOPSENb 2
#endif

#ifndef SCREENSAVERSTARTUPDELAY
#define SCREENSAVERSTARTUPDELAY 5
#endif
#endif
