//JC3248W535C 14.06.2025
//CPU_LOAD - эксперимент. новый виджет.(усреднение загрузки двух ядер)
//одновременное нажатие двумя пальцами на экран - смена режима SD<>Radio
//работает регулировка яркости подсветки дисплея и виджет автозатемнения
//W76W, 4pda

/* Generated by myoptions.h generator - v0.8.1
https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,4,6,7,9,32,42,43,54,64,68&i=1,2,3,4,15,16,17,28,29,30,39,42&v=4,5,-1,15,27,26,25,35,34,39,22,2
Put this file next to yoRadio.ino and restart Arduino IDE. */

#ifndef myoptions_h
#define myoptions_h

// Настройки WiFi. это в ходе экспериментов, можно убрать.
#define WIFI_ATTEMPTS 32  // Увеличиваем количество попыток подключения
#define WIFI_RECONNECT_DELAY 1000  // Задержка перед переподключением в мс
#define WIFI_CONNECT_TIMEOUT 10000  // Таймаут подключения в мс

//#define WROOM_USED                  /*  Set if use WROOM. (To add memory.) aac_decoder must be replased. */
//#define LED_BUILTIN       2           /*  Onboard LED Pin */
//#define LED_INVERT      false       /*  Invert Onboard LED? */
//#define DSP_INVERT_TITLE  false     /*  Инверсные цвета названия станции (заголовок дисплея). По умолчанию "true"  */
//#define EXT_WEATHER       false     /*  Расширенная погода. По умолчанию "true"  */
#define CLOCKFONT_MONO    true  /* Откл/Вкл моношрифтов для часов TFT дисплеев. По умолчанию "true"  */
#define RSSI_DIGIT        true      /* Графический/цифровой значок Wi-Fi. (false - лесенка, true - цифирьки) */
#define BITRATE_FULL      true     /* Значек битрейта. По умолчанию "true" */ 
#define L10N_LANGUAGE RU    /*  Language (EN, RU). More info in yoRadio/locale/displayL10n_(en|ru).h*/


/* Display */
#define DSP_MODEL DSP_AXS15231B

/* **************************************** */

#define DSP_HSPI         false
#define TFT_CS  45                /*  SPI CS pin  */    
#define TFT_RST -1                /*  SPI RST pin.  set to -1 and connect to Esp EN pin */
#define TFT_SCK 47                /*  SPI DC/RS pin  */
#define TFT_D0 21
#define TFT_D1 48
#define TFT_D2 40
#define TFT_D3 39
#define GFX_BL 1 
#define ENABLE_BRIGHTNESS_CONTROL  // Активирует управление яркостью в веб-интерфейсе
//Изначально не было этого параметра, пришлось его добавить вручную 
//так как управление подсветкой тут отличается 
/* **************************************** */

/* === Резистивный тачскрин XPT2046. Раскомментировать, если используется. === */
//#define TOUCH_XPT2046
//#define TS_MODEL TS_MODEL_XPT2046
//#define TS_HSPI true
//#define TS_CS 38   // Используем TS_CS вместо TOUCH_XPT2046_CS
//#define TS_SPIPINS 12, 13, 11  // SCK, MISO, MOSI для HSPI

 //Калибровочные значения для резистивного тачскрина
//#define TS_X_MIN 260
//#define TS_X_MAX 3800
//#define TS_Y_MIN 400
//#define TS_Y_MAX 3800


/*  CAPACITIVE TOUCHSCREEN  Раскомментировать, если используется. */
//#define  TS_MODEL   TS_MODEL_GT911
//#define TS_SDA      8    
//#define TS_SCL      4       
//#define TS_INT      3    
//#define TS_RST      38

#define TS_MODEL TS_MODEL_AXS15231B
#define TS_SDA 4
#define TS_SCL 8
#define TS_INT 3
#define TS_RST -1
/* **************************************** */

/*  I2S DAC    */
#define I2S_DOUT      41//  17                /*  DIN connection. Should be set to 255 if the board is not used */
#define I2S_BCLK       42 //  0              /*  BCLK Bit clock */
#define I2S_LRC        2 //   18            /*  WSEL Left Right Clock */2nd set 543 onboard dac
/* **************************************** */

/*  VS1053 PINS. VS1053 SCK must be connected to pin 18
                 VS1053 MISO must be connected to pin 19
                 VS1053 MOSI must be connected to pin 23  */
#define VS1053_CS       255    /*  XCS pin. Should be set to 255 if the board is not used */
//#define VS1053_DCS    25    /*  XDCS pin.  */
//#define VS1053_DREQ  26    /*  DREQ pin.  */
//#define VS1053_RST    22    /*  XRESET pin. Set to -1 if connected to Esp EN pin */
/*  VS1053 HSPI PINS. VS1053 SCK must be connected to pin 14
                      VS1053 MISO must be connected to pin 12 (+10 KOm на GND)
                      VS1053 MOSI must be connected to pin 13  */
//#define VS_HSPI   true   /*  Use HSPI for VS. По умолчанию "false" */
//#define VS_PATCH_ENABLE true    /*  Use patch for VS. По умолчанию "true" */
/* **************************************** */

// Включение Spectrum Analyzer
#define SPECTRUM_ENABLED       true    // !!Включить Spectrum Analyzer
#define SPECTRUM_USE_PSRAM     true    // Использовать PSRAM для FFT буферов
#define SPECTRUM_BANDS         15      // Количество полос спектра (уменьшено до 15)
#define SPECTRUM_FFT_SIZE      64      // Размер FFT (уменьшен для простоты)
#define SPECTRUM_SMOOTHING     0.7f    // Сглаживание (увеличено для более плавных переходов)
#define SPECTRUM_PEAK_HOLD_TIME 300.0f // Время удержания пиков (мс, уменьшено)
#define SPECTRUM_LOGARITHMIC   false   // Логарифмическая шкала частот (отключено)
#define SPECTRUM_STEREO        false   // Стерео режим (отключено - моно)
#define SPECTRUM_REPLACE_VU    true   // !!Заменить VU-метр на SA
#define SPECTRUM_GAIN          0.06f    // Общее усиление спектра (1.0 = без усиления, 0.05 = -95%)

// Отключение VU-метра (если используем SA) Закомментировать для включения
#define HIDE_VU              // !!для выключения включить SPECTRUM_ENABLED и SPECTRUM_REPLACE_VU 

/*  BUTTONS  */
//#define BTN_LEFT    33     /*  VolDown, Prev */
//#define BTN_CENTER  32    /*  Play, Stop, Show playlist */
//#define BTN_RIGHT   21    /*  VolUp, Next */
//#define BTN_UP      255    /*  Prev, Move Up */
//#define BTN_DOWN    255   /*  Next, Move Down */
//#define BTN_INTERNALPULLUP    false    /*  Enable the weak pull up resistors. По умолчанию "true" */
//#define BTN_LONGPRESS_LOOP_DELAY  200   /*  Delay between calling DuringLongPress event . По умолчанию "200" */
//#define BTN_CLICK_TICKS     300   /*  Event Timing https://github.com/mathertel/OneButton#event-timing По умолчанию "300" */
//#define BTN_PRESS_TICKS     500   /*  Event Timing https://github.com/mathertel/OneButton#event-timing По умолчанию "500" */
/* **************************************** */

/*  ENCODERs  */
//#define ENC_BTNR              7       /*  Правое вращение энкодера (S2, CLK) */
//#define ENC_BTNL              15       /*  Левое вращение энкодера (S1, DT)*/
//#define ENC_BTNB              16       /*  Кнопка энкодера (Key, SW)*/
//#define ENC2_BTNR             34       /*  Правое вращение энкодера-2 (S2, CLK) */
//#define ENC2_BTNL             35       /*  Левое вращение энкодера-2 (S1, DT)*/
//#define ENC2_BTNB             39       /*  Кнопка энкодера-2 (Key, SW)*/
#define ENC_INTERNALPULLUP    true    /*  Enable the weak pull up resistors. По умолчанию "true"  */
#define ENC2_INTERNALPULLUP   true    /*  Enable the weak pull up resistors. По умолчанию "true"  */

/*  SDCARD  */
/*  MISO is the same as D0, MOSI is the same as D1 */
/*  SD VSPI PINS. SD SCK must be connected to pin 18
                  SD MISO must be connected to pin 19
                  SD MOSI must be connected to pin 23  */
/*  SD HSPI PINS. SD SCK must be connected to pin 14
                  SD MISO must be connected to pin 12 (+20 KOm на GND)
                  SD MOSI must be connected to pin 13  */
#define SDC_CS        10              /* Chip Select */
#define SD_SPIPINS    12, 13, 11      /* SCK, MISO, MOSI */
#define SD_HSPI     true              /* use HSPI for SD (SCK=14, MISO=12, MOSI=13) instead of VSPI (by default)  */
/* **************************************** */

/*  Other settings.  */

//#define MUTE_PIN    2             /*  MUTE Pin  (Pin2 - можно совместно использовать с диодом на devboard) */
//#define MUTE_VAL    LOW       /*  Write this to MUTE_PIN when player is stopped. По умолчанию "HIGH" */
#define PLAYER_FORCE_MONO true   /*  mono option on boot - false stereo, true mono. По умолчанию "false" */
//#define I2S_INTERNAL  false /*  If true - use esp32 internal DAC. По умолчанию "false" */
//#define ROTATE_90 false     /*  НЕ РАБОТАЕТ ДЛЯ AXS15231B. НЕ трогать*/
//#define HIDE_VOLPAGE        /* Скрыть страницу "Громкость", ориентируемся по прогрессбару громкости. (МОД nva_lw и Maleksm)  */
//#define HIDE_DATE             /* Скрыть дату. (МОД nva_lw)  */
#define BOOMBOX_STYLE    /* Разные варианты "показометра" VUmetr. Столбик, если строку закоментировать. */
//#define WAKE_PIN              255
#define CPU_LOAD        /* Включить виджет загрузки процессора, комментировать для отключения */


//Можно включать - работает для AXS15231B
//#define AUTOBACKLIGHT(x)    *function*    /*  Autobacklight function. See options.h for exsample  */
//#define AUTOBACKLIGHT_MAX     2500
//#define AUTOBACKLIGHT_MIN     12
//#define DOWN_LEVEL           50      /* lowest level brightness (from 0 to 255, default "2"). (МОД Maleksm) */
//#define DOWN_INTERVAL        60     /* interval for BacklightDown in sec (60 sec = 1 min, default "60"). (МОД Maleksm) */
/* ***************************************** */

/*  Аккумулятор */
//#define BATTERY_OFF
//#define HIDE_BAT                    /* Скрыть показатель уровня заряда и напряжения аккумулятора */
//#define HIDE_VOLT                /*  Скрыть только показатель напряжения аккумулятора */
#define ADC_PIN          5      /* Пин 36 (или 39) для считывания с делителя напряжения аккумулятора. По умолчанию 36. */
#define R1               68    /*  33 Номинал резистора, подключенного к плюсу батареи, в КОм или Ом. По умолчанию 50.  */
#define R2               100     /*  Номинал резистора, подключенного к минусу, в КОм  или Ом. По умолчанию 100. */
#define DELTA_BAT       0.127    /* 0.867 Величина коррекции показаний напряжения батареи в вольтах */
/* *********** ****************************** */
#define GRND_HEIGHT      301     /*  (231 м) Высота местности над уровнем моря в метрах для поправки в давление */

/*  IR control  */
//#define IR_PIN                6
//#define IR_TIMEOUT       80              /*  see kTimeout description in IRremoteESP8266 example */
                   /*  https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/IRrecvDumpV2/IRrecvDumpV2.ino */
/******************************************/

/*  RTC control  */
//#define RTC_MODULE    DS3231  /* или DS1307  */
//#define RTC_SDA       21
//#define RTC_SCL       22
/* **************************************** */


#endif
